[package]
name = "pattern_api_v2"
version = "0.1.0"
authors = ["Marvin Löbel <loebel.marvin@gmail.com>"]

[dependencies]

[dev-dependencies]
pattern_api_v2_test_support = { path = "../pattern_api_v2_test_support" }
